services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - network_a

  webapi:
    build: 
      context: ./web-api
    container_name: web-api
    environment:
      - DB_HOST=mssql-server
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Password
    ports:
      - "8080:8080"
    networks:
      - network_a
    depends_on:
      - mssql

  modsec-nginx:
    build:
      context: ./modsec-nginx
    container_name: modsec-nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network_a
    depends_on:
      - webapi

  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    hostname: juice.shop
    ports:
      - "3000:3000"
    networks:
      - network_a

volumes:
  mssql-data:
  nextcloud-data:

networks:
  network_a:
    driver: bridge
